Refactor Exolnet\Database\Eloquent\Relations\Helper::syncHasMany.
eXolnet/LaravelModule pull request #4
Opened 2015-03-18 03:19 UTC by tomzx

Delete all keys not part of the update upfront, query all related models once and then update them. This way, we prevent the fetching of models one by one using Exolnet\Database\Eloquent\Relations\Helper::getRelatedModel.

2018-09-24 20:18 UTC, xel1045 requested changes
Don't do that!

2018-09-24 20:18 UTC, xel1045 commented on src/Exolnet/Database/Eloquent/Relations/Helper.php
> +use DB;
Nah!

2018-09-24 20:19 UTC, xel1045 requested changes
Haha!

2018-09-24 20:56 UTC, pgrenaud approved these changes

2018-09-24 20:57 UTC, pgrenaud requested changes
Non

2018-09-24 20:57 UTC, pgrenaud approved these changes

2018-09-25 18:12 UTC, xel1045 approved these changes

2019-09-13 12:50 UTC, xel1045 commented
🤷‍♂️

2019-09-13 12:50 UTC, closed without merging